-- MySQL Script generated by MySQL Workbench
-- Sun Dec 17 21:44:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FireBets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FireBets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FireBets` DEFAULT CHARACTER SET utf8 ;
USE `FireBets` ;

-- -----------------------------------------------------
-- Table `FireBets`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FireBets`.`Users` (
  `Login` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `SName` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Balance` DECIMAL(45) NULL,
  PRIMARY KEY (`Login`),
  INDEX `Login_idx` (`Login` ASC))
ENGINE = InnoDB
COMMENT = 'Всё пользователи';


-- -----------------------------------------------------
-- Table `FireBets`.`Matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FireBets`.`Matches` (
  `idMatchs` INT NOT NULL AUTO_INCREMENT,
  `Team1` VARCHAR(45) NOT NULL COMMENT 'Команда 1',
  `Team2` VARCHAR(45) NOT NULL COMMENT 'Команда 2',
  `DateTime` DATETIME(6) NOT NULL COMMENT 'Дата и время проведения матча',
  PRIMARY KEY (`idMatchs`),
  INDEX `Teams_idx` (`Team1` ASC, `Team2` ASC))
ENGINE = InnoDB
COMMENT = 'Матчи';


-- -----------------------------------------------------
-- Table `FireBets`.`Bets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FireBets`.`Bets` (
  `Users_Login` VARCHAR(30) NOT NULL COMMENT 'Логин пользователя создавшего ставку',
  `Matches_idMatchs` INT NOT NULL COMMENT 'ID матча на который стоит ставка',
  `Size` DECIMAL(45) NOT NULL COMMENT 'размер ставки',
  `Type` VARCHAR(45) NOT NULL COMMENT 'тип ставки (победа команды 1, ничья и т.д.)',
  PRIMARY KEY (`Users_Login`, `Matches_idMatchs`),
  INDEX `fk_Bets_Matches1_idx` (`Matches_idMatchs` ASC),
  INDEX `Users_Login_idx` (`Users_Login` ASC),
  CONSTRAINT `fk_Bets_Users1`
    FOREIGN KEY (`Users_Login`)
    REFERENCES `FireBets`.`Users` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bets_Matches1`
    FOREIGN KEY (`Matches_idMatchs`)
    REFERENCES `FireBets`.`Matches` (`idMatchs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Ставки пользователей на матчи';


-- -----------------------------------------------------
-- Table `FireBets`.`Coefficient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FireBets`.`Coefficient` (
  `Matches_idMatchs` INT NOT NULL,
  `CoefTEAM1` INT NOT NULL COMMENT 'Коэфициент на пробеду первой команды',
  `CoefTEAM2` INT NOT NULL COMMENT 'Коэфициент на пробеду второй команды',
  `CoefDRAW` INT NOT NULL COMMENT 'Коэфициент на ничью в матче',
  `CoefExAcc` INT NOT NULL COMMENT 'Коэфициент на предсказание точного счёта',
  PRIMARY KEY (`Matches_idMatchs`),
  CONSTRAINT `fk_Coefficient_Matches1`
    FOREIGN KEY (`Matches_idMatchs`)
    REFERENCES `FireBets`.`Matches` (`idMatchs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Коэфициенты на матч';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;